In [21]:
# import paddle.fluid as fluid
import paddle
import numpy as np
import os
import matplotlib.pyplot as plt

In [4]:
paddle.utils.run_check()

Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.


In [6]:
paddle.dataset.uci_housing.train()

<function paddle.dataset.uci_housing.train.<locals>.reader()>

In [7]:
#设置默认的全局dtype为float64
paddle.set_default_dtype("float64")
#下载数据
print('下载并加载训练数据')
train_dataset = paddle.text.datasets.UCIHousing(mode='train')
eval_dataset = paddle.text.datasets.UCIHousing(mode='test')
train_loader = paddle.io.DataLoader(train_dataset, batch_size=32, shuffle=True)
eval_loader = paddle.io.DataLoader(eval_dataset, batch_size = 8, shuffle=False)

print('加载完成')

下载并加载训练数据
加载完成


In [128]:
train_dataset.data[0]

array([-0.0405441 ,  0.06636364, -0.32356227, -0.06916996, -0.03435197,
        0.05563625, -0.03475696,  0.02682186, -0.37171335, -0.21419304,
       -0.33569506,  0.10143217, -0.21172912, 24.        ])

In [129]:
train_dataset[0]

(array([-0.0405441 ,  0.06636364, -0.32356227, -0.06916996, -0.03435197,
         0.05563625, -0.03475696,  0.02682186, -0.37171335, -0.21419304,
        -0.33569506,  0.10143217, -0.21172912]),
 array([24.]))

In [23]:
class R(paddle.nn.Layer):
    def __init__(self):
        super(R,self).__init__()
        self.li=paddle.nn.Linear(13,1,None)
    def forward(self,inputs):
        return self.li(inputs)

In [20]:
Batch=0
Batchs=[]
all_train_accs=[]
def draw_train_acc(Batchs, train_accs):
    title="training accs"
    plt.title(title, fontsize=24)
    plt.xlabel("batch", fontsize=14)
    plt.ylabel("acc", fontsize=14)
    plt.plot(Batchs, train_accs, color='green', label='training accs')
    plt.legend()
    plt.grid()
    plt.show()

all_train_loss=[]
def draw_train_loss(Batchs, train_loss):
    title="training loss"
    plt.title(title, fontsize=24)
    plt.xlabel("batch", fontsize=14)
    plt.ylabel("loss", fontsize=14)
    plt.plot(Batchs, train_loss, color='red', label='training loss')
    plt.legend()
    plt.grid()
    plt.show()

In [110]:
model=R() # 模型实例化
model.train() # 训练模式
mse_loss = paddle.nn.MSELoss()
opt=paddle.optimizer.SGD(learning_rate=0.0005, parameters=model.parameters())

In [122]:
model.train()
for _ in range(100):
    for i,data in enumerate(train_loader):
        pred=model(data[0])
        loss=mse_loss(pred,data[1])
        loss.backward()
        opt.step()
        opt.clear_grad()

In [118]:
model.parameters()

[Parameter containing:
 Tensor(shape=[13, 1], dtype=float64, place=Place(cpu), stop_gradient=False,
        [[-0.53826329],
         [ 1.52406932],
         [-2.03951685],
         [ 1.86732021],
         [-2.15065151],
         [ 3.68561169],
         [-1.99898438],
         [ 0.45627942],
         [-3.00464846],
         [-2.83157585],
         [-3.62130116],
         [ 1.92316096],
         [-3.68497106]]),
 Parameter containing:
 Tensor(shape=[1], dtype=float64, place=Place(cpu), stop_gradient=False,
        [22.29476972])]

In [123]:
model.eval()
for i,data in enumerate(eval_loader):
    pred=model(data[0])
    print(pred.numpy()[0],data[1].numpy()[0])

[13.47636115] [8.5]
[10.03986805] [17.9]
[16.32427969] [16.7]
[14.43038117] [11.]
[14.3615688] [9.6]
[13.77670142] [10.8]
[16.34974118] [16.1]
[16.30016596] [16.4]
[16.53250635] [19.1]
[16.77943955] [16.7]
[17.84635223] [20.6]
[18.12524311] [20.1]
[21.71820731] [16.8]
