In [3]:
import numpy as np

In [18]:
from sklearn.metrics import accuracy_score,classification_report
from sklearn.neighbors import KNeighborsClassifier

In [29]:
X1=np.random.randint(0,10,[5,5])
y1=np.zeros([5,1],dtype=int)
X2=np.random.randint(10,20,[5,5])
y2=np.ones([5,1],dtype=int)
X=np.concatenate((X1,X2),0)
y=np.concatenate((y1,y2),0)
print(X,y)

[[ 4  8  3  3  1]
 [ 9  7  3  7  6]
 [ 8  9  2  0  5]
 [ 2  8  7  1  0]
 [ 5  9  5  3  3]
 [10 15 13 15 15]
 [11 19 14 18 17]
 [13 10 10 10 18]
 [19 15 11 17 19]
 [13 19 14 16 16]] [[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [30]:
knc = KNeighborsClassifier(n_neighbors=2)
knc.fit(X,y)

D:\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=2)

In [31]:
X_test=np.random.randint(0,20,[10,5])
print(X_test,knc.predict(X_test))

[[ 8 19 19  5  2]
 [ 3 15  2  5  8]
 [ 6  6  5  7  3]
 [ 0 14  1 16 19]
 [ 7  5  2 14 18]
 [ 3  7 17  8 18]
 [15 16  0  9  5]
 [ 7 13 13 11 16]
 [10  1  1  6 10]
 [15 10 11 17 14]] [0 0 0 1 0 1 0 1 0 1]
